PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX xhtml: <http://www.w3.org/1999/xhtml> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX dc: <http://purl.org/dc/terms/> 
PREFIX dctype: <http://purl.org/dc/dcmitype/> 
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX csvw: <http://www.w3.org/ns/csvw#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://cldf.clld.org/v1.0/terms.rdf#>

# ID,Name,Description,Concepticon_ID
# jq '.tables[]|select(.url=="parameters.csv")' src/Wordlist-metadata.json

# partially formalized in ./src/Wordlist-metadata.json, only
CONSTRUCT {
	?about terms:id ?ID;
		terms:name ?Name;
		terms:description ?Description;
		terms:concepticonReference ?concepticon.
} WHERE {
	BIND(IRI(concat('http://ids.clld.org/parameters/',?ID)) AS ?about)
	BIND(IRI(concat('http://concepticon.clld.org/parameters/',?Concepticon_ID)) AS ?concepticon)
}
